import Head from "next/head";
import React, { useEffect, useState } from "react";
import { Box, Grid, GridItem } from "@chakra-ui/react";
import { Header } from "@/components/Header";
import { PersonalBest } from "@/components/PersonalBest";
import { SessionBest } from "@/components/SessionBest";
import { Lap } from "@/components/Lap";
import io from "Socket.IO-client";

import { emptyLapData } from "@/utils/initData";

let socket;
const Home = () => {
  const [lapData, setLapData] = useState(emptyLapData);
  const [currentLapNum, setCurrentLapNum] = useState(1);
  const [sessionData, setSessionData] = useState();
  useEffect(() => {
    const socketInitializer = async () => {
      await fetch("/api/socket");
      socket = io();

      socket.on("lapDataUpdate", (updatedData) => {
        setLapData(updatedData);

        if (updatedData.m_lapData[0].m_currentLapNum != currentLapNum) {
          setCurrentLapNum(updatedData.m_lapData[0].m_currentLapNum);
        }
      });
      socket.on("sessionDataUpdate", (updatedData) => {
        setSessionData(updatedData);
        console.log(sessionData);
      });
    };
    socketInitializer();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin={"anonymous"}
        />
      </Head>
      <Box maxW={"sm"} bg={"#15151E"}>
        <Grid
          templateAreas={`"header"
                  "personalBest"
                  "sessionBest"
                  "sector1" "sector2" "sector3"`}
          maxH="18.75rem"
        >
          <GridItem h={"3.25rem"} area={"header"} fontSize={"xl"}>
            <Header />
          </GridItem>
          <GridItem maxH={"5rem"} area={"personalBest"} p={1}>
            <PersonalBest />
          </GridItem>
          <GridItem
            maxH={"5rem"}
            area={"sessionBest"}
            p={1}
            marginBottom={"0.5rem"}
          >
            <SessionBest />
          </GridItem>
          <Lap data={lapData} currentLap={currentLapNum} />
        </Grid>
      </Box>
    </>
  );
};

export default Home;
